# Generated by Django 4.0.3 on 2022-03-19 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend_ship_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendShipTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendShipTestAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=200)),
                ('result', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendShipTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('answers', models.ManyToManyField(to='friend_ship_test.friendshiptestanswers')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('friend_ship_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_ship_test.friendshiptest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendShipTestQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('friend_ship_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_ship_test.friendshiptest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_ship_test.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendShipTestInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invite_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('friend_ship_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_ship_test.friendshiptest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='friendshiptestanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friend_ship_test.friendshiptestquestionnaire'),
        ),
        migrations.AddField(
            model_name='friendshiptest',
            name='questions',
            field=models.ManyToManyField(through='friend_ship_test.FriendShipTestQuestionnaire', to='friend_ship_test.question'),
        ),
    ]
