# Generated by Django 4.0.3 on 2022-03-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_ship_test', '0004_rename_friendshiptestanswers_friendshiptestanswer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendshiptest',
            index=models.Index(fields=['uuid'], name='friend_ship_uuid_50cb3c_idx'),
        ),
    ]
